In [1]:
from numpy import array, zeros, dot, diag

A= array([[4, -1, 0, -1], [-1, 4, -1, 0], [-1, 0, -1, 4], [0, -1, 4, -1]])

B= array([[30], [60], [70], [40]])


def GEPP(A, b):
    
    n= len(A)
    if b.size != n:
        raise ValueError("Invalid argument: incompatible sizes between A y b", b.size, n)
        
    for k in range(n -1):
        
        maxindex = abs(A[k:, k]). argmax() + k
        if A[maxindex, k] == 0:
            raise ValueError("Matrix is singular")
            
        if maxindex != k:
            A[[k, maxindex]] = A[[maxindex, k]]
            b[[k, maxindex]] = b[[maxindex, k]]
            
        for row in range (k + 1, n):
            multiplier = A[row][k] / A[k][k]
            
            A[row][k] = multiplier
            
            for col in range (k +1, n):
                A[row][col]= A[row][col] - multiplier * A[k][col]
                b[row] = b[row] - multiplier * b[k]
                
                x = zeros(n)
                k=n -1
                x[k] = b[k] / A[k, k]
                
                while k>= 0:
                    x[k] = (b[k] - dot(A[k, k +1:], x[k +1:])) / A [k, k]
                    k = k -1
                return x
            
print('La matriz ingresada es:')
print(A,B)
Aug = GEPP(A, B)
print('Las soluciones para el sistema de ecuaciones son.....X_1, X_2, X_3, X_4')
print (Aug)
    
    
    

La matriz ingresada es:
[[ 4 -1  0 -1]
 [-1  4 -1  0]
 [-1  0 -1  4]
 [ 0 -1  4 -1]] [[30]
 [60]
 [70]
 [40]]
Las soluciones para el sistema de ecuaciones son.....X_1, X_2, X_3, X_4
[ -16.08333333  -54.33333333 -230.          -40.        ]


In [2]:
# Creado por Ismael Salazar