In [26]:
#Método de sustitución regresiva para matrices 3 X 3
import numpy as np
#Trabajaremos con la libreria numpy para poder crear matrices

#Creamos la matriz
A=np.array([[12,6,-8],
            [-20,-6,12],
            [-8,8,10]])

#Armo mi vector Pivote
b=np.array([12,-7,-18])

print("Matriz Ingresada")
print(A,b)
print(" ")

N=len(b)
x=np.zeros(N)

for i in range(N-1):
#Armo los reglones Pivote, Marcados con la "i" 

    b[i]=b[i]/A[i][i]
    A[i]=A[i]/A[i][i]
    print(A,b)
    print(" ")
    for k in range(i+1,N):
#Reduzco las filas aplicando los pivotes para hacer cero los numeros debajo de la 
#Diagonal Principal
        b[k]=b[k]-A[k][i]*b[i]
        A[k]=A[k]-A[k][i]*A[i]
        print(A,b)
        print(" ")
    
i=N-1
b[i]=b[i]/A[i][i]
A[i]=A[i]/A[i][i]

#Imprimo la matriz final
    
print("La matriz reducidad es:")    
print(A,b)

Matriz Ingresada
[[ 12   6  -8]
 [-20  -6  12]
 [ -8   8  10]] [ 12  -7 -18]
 
[[  1   0   0]
 [-20  -6  12]
 [ -8   8  10]] [  1  -7 -18]
 
[[ 1  0  0]
 [ 0 -6 12]
 [-8  8 10]] [  1  13 -18]
 
[[ 1  0  0]
 [ 0 -6 12]
 [ 0  8 10]] [  1  13 -10]
 
[[ 1  0  0]
 [ 0  1 -2]
 [ 0  8 10]] [  1  -2 -10]
 
[[ 1  0  0]
 [ 0  1 -2]
 [ 0  0 26]] [ 1 -2  6]
 
La matriz reducidad es:
[[ 1  0  0]
 [ 0  1 -2]
 [ 0  0  1]] [ 1 -2  0]


In [19]:
#Código creado por Ismael Salazar